// ═══════════════════════════════════════════════════════════
//  LAYOUTS
//  keys: event.code → [default, shift, altgr]
//  null = no character on that layer
// ═══════════════════════════════════════════════════════════
const LAYOUTS = {

// ──────────────────────────────────────────────────────────
"ch-fr-qwertz": {
  name:     "Swiss French QWERTZ",
  region:   "CH-FR",
  physical: "iso",
  lang:     "fr-CH",
  keys: {
    // Number row
    Backquote:    ["§",  "°",  "¦"  ],
    Digit1:       ["1",  "+",  "|"  ],
    Digit2:       ["2",  '"',  "@"  ],
    Digit3:       ["3",  "*",  "#"  ],
    Digit4:       ["4",  "ç",  null ],
    Digit5:       ["5",  "%",  null ],
    Digit6:       ["6",  "&",  "¬"  ],
    Digit7:       ["7",  "/",  "|"  ],
    Digit8:       ["8",  "(",  "¢"  ],
    Digit9:       ["9",  ")",  null ],
    Digit0:       ["0",  "=",  null ],
    Minus:        ["'",  "?",  "´"  ],
    Equal:        ["^",  "`",  "~"  ],
    // Top row (QWERTZ — Y/Z swapped vs QWERTY)
    KeyQ:         ["q",  "Q",  null ],
    KeyW:         ["w",  "W",  null ],
    KeyE:         ["e",  "E",  "€"  ],
    KeyR:         ["r",  "R",  null ],
    KeyT:         ["t",  "T",  null ],
    KeyY:         ["z",  "Z",  null ],  // physical Y key → Z character
    KeyU:         ["u",  "U",  null ],
    KeyI:         ["i",  "I",  null ],
    KeyO:         ["o",  "O",  null ],
    KeyP:         ["p",  "P",  null ],
    BracketLeft:  ["è",  "ü",  "["  ],
    BracketRight: ["¨",  "!",  "]"  ],  // ¨ = dead diaeresis
    Backslash:    ["$",  "£",  "}"  ],
    // Home row
    KeyA:         ["a",  "A",  null ],
    KeyS:         ["s",  "S",  null ],
    KeyD:         ["d",  "D",  null ],
    KeyF:         ["f",  "F",  null ],
    KeyG:         ["g",  "G",  null ],
    KeyH:         ["h",  "H",  null ],
    KeyJ:         ["j",  "J",  null ],
    KeyK:         ["k",  "K",  null ],
    KeyL:         ["l",  "L",  null ],
    Semicolon:    ["é",  "ö",  null ],
    Quote:        ["à",  "ä",  "{"  ],
    // Bottom row (ISO has IntlBackslash between LShift and Y/Z)
    IntlBackslash:["<",  ">",  "\\" ],
    KeyZ:         ["y",  "Y",  null ],  // physical Z key → Y character
    KeyX:         ["x",  "X",  null ],
    KeyC:         ["c",  "C",  null ],
    KeyV:         ["v",  "V",  null ],
    KeyB:         ["b",  "B",  null ],
    KeyN:         ["n",  "N",  null ],
    KeyM:         ["m",  "M",  null ],
    Comma:        [",",  ";",  null ],
    Period:       [".",  ":",  null ],
    Slash:        ["-",  "_",  null ],
    Space:        [" ",  " ",  " "  ],
    Enter:        ["\n", "\n", null ],
  },
  rows: [
    [["Backquote"],["Digit1"],["Digit2"],["Digit3"],["Digit4"],["Digit5"],["Digit6"],["Digit7"],["Digit8"],["Digit9"],["Digit0"],["Minus"],["Equal"],["Backspace","w2","⌫"]],
    [["Tab","w15","⇥"],["KeyQ"],["KeyW"],["KeyE"],["KeyR"],["KeyT"],["KeyY"],["KeyU"],["KeyI"],["KeyO"],["KeyP"],["BracketLeft"],["BracketRight"]],
    [["CapsLock","w175","⇪"],["KeyA"],["KeyS"],["KeyD"],["KeyF"],["KeyG"],["KeyH"],["KeyJ"],["KeyK"],["KeyL"],["Semicolon"],["Quote"],["Backslash"],["Enter","w2","↵"]],
    [["ShiftLeft","w12","⇧"],["IntlBackslash"],["KeyZ"],["KeyX"],["KeyC"],["KeyV"],["KeyB"],["KeyN"],["KeyM"],["Comma"],["Period"],["Slash"],["ShiftRight","w25","⇧"]],
    [["ControlLeft","w15","Ctrl"],["MetaLeft","","⌘"],["AltLeft","","Alt"],["Space","w65",""],["AltRight","","AltGr"],["ContextMenu","","☰"],["ControlRight","w15","Ctrl"]],
  ],
},

// ──────────────────────────────────────────────────────────
"en-us-qwerty": {
  name:     "English QWERTY (US)",
  region:   "US",
  physical: "ansi",
  lang:     "en-US",
  keys: {
    Backquote:    ["`",  "~",  null ],
    Digit1:       ["1",  "!",  null ],
    Digit2:       ["2",  "@",  null ],
    Digit3:       ["3",  "#",  null ],
    Digit4:       ["4",  "$",  null ],
    Digit5:       ["5",  "%",  null ],
    Digit6:       ["6",  "^",  null ],
    Digit7:       ["7",  "&",  null ],
    Digit8:       ["8",  "*",  null ],
    Digit9:       ["9",  "(",  null ],
    Digit0:       ["0",  ")",  null ],
    Minus:        ["-",  "_",  null ],
    Equal:        ["=",  "+",  null ],
    KeyQ:         ["q",  "Q",  null ],
    KeyW:         ["w",  "W",  null ],
    KeyE:         ["e",  "E",  null ],
    KeyR:         ["r",  "R",  null ],
    KeyT:         ["t",  "T",  null ],
    KeyY:         ["y",  "Y",  null ],
    KeyU:         ["u",  "U",  null ],
    KeyI:         ["i",  "I",  null ],
    KeyO:         ["o",  "O",  null ],
    KeyP:         ["p",  "P",  null ],
    BracketLeft:  ["[",  "{",  null ],
    BracketRight: ["]",  "}",  null ],
    Backslash:    ["\\", "|",  null ],
    KeyA:         ["a",  "A",  null ],
    KeyS:         ["s",  "S",  null ],
    KeyD:         ["d",  "D",  null ],
    KeyF:         ["f",  "F",  null ],
    KeyG:         ["g",  "G",  null ],
    KeyH:         ["h",  "H",  null ],
    KeyJ:         ["j",  "J",  null ],
    KeyK:         ["k",  "K",  null ],
    KeyL:         ["l",  "L",  null ],
    Semicolon:    [";",  ":",  null ],
    Quote:        ["'",  '"',  null ],
    KeyZ:         ["z",  "Z",  null ],
    KeyX:         ["x",  "X",  null ],
    KeyC:         ["c",  "C",  null ],
    KeyV:         ["v",  "V",  null ],
    KeyB:         ["b",  "B",  null ],
    KeyN:         ["n",  "N",  null ],
    KeyM:         ["m",  "M",  null ],
    Comma:        [",",  "<",  null ],
    Period:       [".",  ">",  null ],
    Slash:        ["/",  "?",  null ],
    Space:        [" ",  " ",  " "  ],
    Enter:        ["\n", "\n", null ],
  },
  rows: [
    [["Backquote"],["Digit1"],["Digit2"],["Digit3"],["Digit4"],["Digit5"],["Digit6"],["Digit7"],["Digit8"],["Digit9"],["Digit0"],["Minus"],["Equal"],["Backspace","w2","⌫"]],
    [["Tab","w15","⇥"],["KeyQ"],["KeyW"],["KeyE"],["KeyR"],["KeyT"],["KeyY"],["KeyU"],["KeyI"],["KeyO"],["KeyP"],["BracketLeft"],["BracketRight"],["Backslash"]],
    [["CapsLock","w175","⇪"],["KeyA"],["KeyS"],["KeyD"],["KeyF"],["KeyG"],["KeyH"],["KeyJ"],["KeyK"],["KeyL"],["Semicolon"],["Quote"],["Enter","w2","↵"]],
    [["ShiftLeft","w225","⇧"],["KeyZ"],["KeyX"],["KeyC"],["KeyV"],["KeyB"],["KeyN"],["KeyM"],["Comma"],["Period"],["Slash"],["ShiftRight","w25","⇧"]],
    [["ControlLeft","w15","Ctrl"],["MetaLeft","","⌘"],["AltLeft","","Alt"],["Space","w65",""],["AltRight","","AltGr"],["ContextMenu","","☰"],["ControlRight","w15","Ctrl"]],
  ],
},

// ──────────────────────────────────────────────────────────
"fr-azerty": {
  name:     "French AZERTY",
  region:   "FR",
  physical: "iso",
  lang:     "fr-FR",
  keys: {
    Backquote:    ["²",  null, null ],
    Digit1:       ["&",  "1",  null ],
    Digit2:       ["é",  "2",  "~"  ],
    Digit3:       ['"',  "3",  "#"  ],
    Digit4:       ["'",  "4",  "{"  ],
    Digit5:       ["(",  "5",  "["  ],
    Digit6:       ["-",  "6",  "|"  ],
    Digit7:       ["è",  "7",  "`"  ],
    Digit8:       ["_",  "8",  "\\" ],
    Digit9:       ["ç",  "9",  "^"  ],
    Digit0:       ["à",  "0",  "@"  ],
    Minus:        [")",  "°",  "]"  ],
    Equal:        ["=",  "+",  "}"  ],
    KeyQ:         ["a",  "A",  null ],
    KeyW:         ["z",  "Z",  null ],
    KeyE:         ["e",  "E",  "€"  ],
    KeyR:         ["r",  "R",  null ],
    KeyT:         ["t",  "T",  null ],
    KeyY:         ["y",  "Y",  null ],
    KeyU:         ["u",  "U",  null ],
    KeyI:         ["i",  "I",  null ],
    KeyO:         ["o",  "O",  null ],
    KeyP:         ["p",  "P",  null ],
    BracketLeft:  ["^",  "¨",  null ],
    BracketRight: ["$",  "£",  "¤"  ],
    Backslash:    ["*",  "μ",  null ],
    KeyA:         ["q",  "Q",  null ],
    KeyS:         ["s",  "S",  null ],
    KeyD:         ["d",  "D",  null ],
    KeyF:         ["f",  "F",  null ],
    KeyG:         ["g",  "G",  null ],
    KeyH:         ["h",  "H",  null ],
    KeyJ:         ["j",  "J",  null ],
    KeyK:         ["k",  "K",  null ],
    KeyL:         ["l",  "L",  null ],
    Semicolon:    ["m",  "M",  null ],
    Quote:        ["ù",  "%",  null ],
    IntlBackslash:["<",  ">",  null ],
    KeyZ:         ["w",  "W",  null ],
    KeyX:         ["x",  "X",  null ],
    KeyC:         ["c",  "C",  null ],
    KeyV:         ["v",  "V",  null ],
    KeyB:         ["b",  "B",  null ],
    KeyN:         ["n",  "N",  null ],
    KeyM:         [",",  "?",  null ],
    Comma:        [";",  ".",  null ],
    Period:       [":",  "/",  null ],
    Slash:        ["!",  "§",  null ],
    Space:        [" ",  " ",  " "  ],
    Enter:        ["\n", "\n", null ],
  },
  rows: [
    [["Backquote"],["Digit1"],["Digit2"],["Digit3"],["Digit4"],["Digit5"],["Digit6"],["Digit7"],["Digit8"],["Digit9"],["Digit0"],["Minus"],["Equal"],["Backspace","w2","⌫"]],
    [["Tab","w15","⇥"],["KeyQ"],["KeyW"],["KeyE"],["KeyR"],["KeyT"],["KeyY"],["KeyU"],["KeyI"],["KeyO"],["KeyP"],["BracketLeft"],["BracketRight"],["Backslash"]],
    [["CapsLock","w175","⇪"],["KeyA"],["KeyS"],["KeyD"],["KeyF"],["KeyG"],["KeyH"],["KeyJ"],["KeyK"],["KeyL"],["Semicolon"],["Quote"],["Enter","w2","↵"]],
    [["ShiftLeft","w12","⇧"],["IntlBackslash"],["KeyZ"],["KeyX"],["KeyC"],["KeyV"],["KeyB"],["KeyN"],["KeyM"],["Comma"],["Period"],["Slash"],["ShiftRight","w25","⇧"]],
    [["ControlLeft","w15","Ctrl"],["MetaLeft","","⌘"],["AltLeft","","Alt"],["Space","w65",""],["AltRight","","AltGr"],["ContextMenu","","☰"],["ControlRight","w15","Ctrl"]],
  ],
},

}; // end LAYOUTS

// ═══════════════════════════════════════════════════════════
//  NUMPAD
// ═══════════════════════════════════════════════════════════
const NUMPAD_KEYS = {
  NumLock:        [null],
  NumpadDivide:   ["/"],
  NumpadMultiply: ["*"],
  NumpadSubtract: ["-"],
  Numpad7:        ["7"],
  Numpad8:        ["8"],
  Numpad9:        ["9"],
  NumpadAdd:      ["+"],
  Numpad4:        ["4"],
  Numpad5:        ["5"],
  Numpad6:        ["6"],
  NumpadEnter:    ["\n"],
  Numpad1:        ["1"],
  Numpad2:        ["2"],
  Numpad3:        ["3"],
  NumpadDecimal:  ["."],
  Numpad0:        ["0"],
};

// r/c = 1-based grid row/col start; rs/cs = row/col span (default 1)
const NUMPAD_LAYOUT = [
  { code:"NumLock",        r:1, c:1,        label:"⇭" },
  { code:"NumpadDivide",   r:1, c:2 },
  { code:"NumpadMultiply", r:1, c:3 },
  { code:"NumpadSubtract", r:1, c:4 },
  { code:"Numpad7",        r:2, c:1 },
  { code:"Numpad8",        r:2, c:2 },
  { code:"Numpad9",        r:2, c:3 },
  { code:"NumpadAdd",      r:2, c:4, rs:2 },  // tall: rows 2-3
  { code:"Numpad4",        r:3, c:1 },
  { code:"Numpad5",        r:3, c:2 },
  { code:"Numpad6",        r:3, c:3 },
  { code:"Numpad1",        r:4, c:1 },
  { code:"Numpad2",        r:4, c:2 },
  { code:"Numpad3",        r:4, c:3 },
  { code:"NumpadEnter",    r:4, c:4, rs:2, label:"↵" },  // tall: rows 4-5
  { code:"Numpad0",        r:5, c:1, cs:2 },              // wide: cols 1-2
  { code:"NumpadDecimal",  r:5, c:3 },
];

// ═══════════════════════════════════════════════════════════
//  SPOKEN NAMES FOR SYMBOLS
// ═══════════════════════════════════════════════════════════
const SPOKEN_FR = {
  " ":"espace", "\n":"entrée", "@":"arobase", "#":"dièse", "&":"esperluette",
  "€":"euro", "$":"dollar", "£":"livre sterling", "¢":"cent",
  "%":"pourcent", "^":"accent circonflexe", "¨":"tréma",
  "~":"tilde", "`":"accent grave", "´":"accent aigu",
  "§":"paragraphe", "°":"degré", "²":"carré",
  "|":"barre verticale", "\\":"antislash", "/":"slash",
  '"':"guillemet", "'":"apostrophe", "<":"inférieur à",
  ">":"supérieur à", "¬":"signe non", "¦":"barre brisée",
  "*":"astérisque", "+":"plus", "-":"tiret", "_":"underscore",
  "=":"égal", "?":"point d'interrogation", "!":"point d'exclamation",
  ",":"virgule", ".":"point", ";":"point-virgule", ":":"deux points",
  "(":"parenthèse ouvrante", ")":"parenthèse fermante",
  "[":"crochet ouvrant", "]":"crochet fermant",
  "{":"accolade ouvrante", "}":"accolade fermante",
  "ç":"cé cédille", "é":"é accent aigu", "è":"è accent grave",
  "à":"à accent grave", "ù":"u accent grave", "ü":"u tréma",
  "ö":"o tréma", "ä":"a tréma", "ê":"e accent circonflexe",
  "¢":"cent", "£":"livre", "¤":"devise",
};

const SPOKEN_EN = {
  " ":"space", "\n":"enter", "@":"at sign", "#":"hash", "&":"ampersand",
  "€":"euro", "$":"dollar", "£":"pound", "¢":"cent",
  "%":"percent", "^":"caret", "~":"tilde", "`":"backtick",
  "§":"section", "°":"degree", "|":"pipe", "\\":"backslash",
  "/":"slash", '"':"double quote", "'":"apostrophe",
  "<":"less than", ">":"greater than", "*":"asterisk",
  "+":"plus", "-":"dash", "_":"underscore", "=":"equals",
  "?":"question mark", "!":"exclamation", ",":"comma",
  ".":"period", ";":"semicolon", ":":"colon",
  "(":"open paren", ")":"close paren",
  "[":"open bracket", "]":"close bracket",
  "{":"open brace", "}":"close brace",
};

// ═══════════════════════════════════════════════════════════
//  DEAD KEY COMPOSITION TABLES
// ═══════════════════════════════════════════════════════════
const DEAD_COMPOSE = {
  "^": { a:"â",e:"ê",i:"î",o:"ô",u:"û",A:"Â",E:"Ê",I:"Î",O:"Ô",U:"Û" },
  "¨": { a:"ä",e:"ë",i:"ï",o:"ö",u:"ü",y:"ÿ",A:"Ä",E:"Ë",I:"Ï",O:"Ö",U:"Ü",Y:"Ÿ" },
  "`": { a:"à",e:"è",i:"ì",o:"ò",u:"ù",A:"À",E:"È",I:"Ì",O:"Ò",U:"Ù" },
  "´": { a:"á",e:"é",i:"í",o:"ó",u:"ú",y:"ý",A:"Á",E:"É",I:"Í",O:"Ó",U:"Ú",Y:"Ý" },
  "~": { a:"ã",n:"ñ",o:"õ",A:"Ã",N:"Ñ",O:"Õ" },
};
